In [4]:
import numpy as np

# Dataset
data = np.array([
    [0, 2, 1],
    [1, 7, 1],
    [2, 6, 3],
    [5, 1, 4],
    [3, 3, 4]
])

# Function for Linear normalization
def z_score_normalization(data):
    print(r"""
        ┌┐┌┌─┐┬─┐┌┬┐┌─┐┬  ┬┌─┐┌─┐┌─┐┬  ┬  ┬┌┐┌┌─┐┌─┐┬─┐
        ││││ │├┬┘│││├─┤│  │└─┐├─┤└─┐│  │  ││││├┤ ├─┤├┬┘
        ┘└┘└─┘┴└─┴ ┴┴ ┴┴─┘┴└─┘┴ ┴└─┘┴  ┴─┘┴┘└┘└─┘┴ ┴┴└─
    """)
    print("Data Asli:")
    print(data)
    
    # Calculate mean and standard deviation for each feature
    means = np.mean(data, axis=0)
    std_devs = np.std(data, axis=0, ddof=1)
    
    # Step-by-step explanation for calculating mean and standard deviation
    # Display mean and standard deviation for each feature
    print("-"*10,"Mean (x̄) untuk setiap fitur:","-"*10)
    for j in range(data.shape[1]):
        print(f"Fitur {j+1}: {means[j]:.4f}")
    print("\nLangkah-langkah perhitungan mean:")
    # Calculate and show mean for each feature
    for j in range(data.shape[1]):
        feature_data = data[:, j]
        mean = np.mean(feature_data)
        print(f"\nFitur {j+1}:")
        print(f"  Data: {feature_data}")
        print(f"  x̄ = (Hasil Jumlah data) / (Banyak Data):")
        print(f"  Mean (x̄) = {np.sum(feature_data)} / {len(feature_data)} = {mean:.4f}")
    print("="*70)
    print("-"*10,"Standard Deviation (σ) untuk setiap fitur:","-"*10)
    for j in range(data.shape[1]):
        print(f"Fitur {j+1}: {std_devs[j]:.4f}")
    
    # Calculate and show standard deviation for each feature
    print("\nLangkah-langkah perhitungan deviasi standar:")
    for j in range(data.shape[1]):
        feature_data = data[:, j]
        mean = np.mean(feature_data)
        squared_diff = (feature_data - mean) ** 2
        std_dev = np.sqrt(np.sum(squared_diff) / (len(feature_data) - 1))  # Sample std deviation (ddof=1)
        print(f"\nFitur {j+1}:")
        print(f"  Data: {feature_data}")
        print(f"  Deviasi Standar (σ) = sqrt(Sum of (Data - Mean)²) / (Jumlah Data - 1)")
        print(f"  σ = sqrt({np.sum(squared_diff)} / {len(feature_data) - 1}) = {std_dev:.4f}")
    
    print("="*70)
    # Calculate Linear normalization for each element
    normalized_data = (data - means) / std_devs
    
    # Display step-by-step Linear calculations
    print("-"*10,"Langkah-langkah perhitungan normalisasi Linear:","-"*10)
    for j in range(data.shape[1]):
        print(f"\nFitur {j+1}:")
        for i in range(data.shape[0]):
            z_value = (data[i, j] - means[j]) / std_devs[j]
            print(f"  x̄ {i+1}{j+1}: {data[i, j]} -> ({data[i, j]} - {means[j]:.4f}) / {std_devs[j]:.4f} = {z_value:.4f}")
    
    # Display normalized data
    print("\nData setelah normalisasi:")
    print(np.round(normalized_data, 4))
    return normalized_data

# Run the normalization
normalized_data = z_score_normalization(data)


        ┌┐┌┌─┐┬─┐┌┬┐┌─┐┬  ┬┌─┐┌─┐┌─┐┬  ┬  ┬┌┐┌┌─┐┌─┐┬─┐
        ││││ │├┬┘│││├─┤│  │└─┐├─┤└─┐│  │  ││││├┤ ├─┤├┬┘
        ┘└┘└─┘┴└─┴ ┴┴ ┴┴─┘┴└─┘┴ ┴└─┘┴  ┴─┘┴┘└┘└─┘┴ ┴┴└─
    
Data Asli:
[[0 2 1]
 [1 7 1]
 [2 6 3]
 [5 1 4]
 [3 3 4]]
---------- Mean (x̄) untuk setiap fitur: ----------
Fitur 1: 2.2000
Fitur 2: 3.8000
Fitur 3: 2.6000

Langkah-langkah perhitungan mean:

Fitur 1:
  Data: [0 1 2 5 3]
  x̄ = (Hasil Jumlah data) / (Banyak Data):
  Mean (x̄) = 11 / 5 = 2.2000

Fitur 2:
  Data: [2 7 6 1 3]
  x̄ = (Hasil Jumlah data) / (Banyak Data):
  Mean (x̄) = 19 / 5 = 3.8000

Fitur 3:
  Data: [1 1 3 4 4]
  x̄ = (Hasil Jumlah data) / (Banyak Data):
  Mean (x̄) = 13 / 5 = 2.6000
---------- Standard Deviation (σ) untuk setiap fitur: ----------
Fitur 1: 1.9235
Fitur 2: 2.5884
Fitur 3: 1.5166

Langkah-langkah perhitungan deviasi standar:

Fitur 1:
  Data: [0 1 2 5 3]
  Deviasi Standar (σ) = sqrt(Sum of (Data - Mean)²) / (Jumlah Data - 1)
  σ = sqrt(14.8 / 4) = 1.9235

Fitur 2:
  Data: [2 7 6 1 3]
 

In [3]:

import numpy as np
# Dataset
data = np.array([
    [0, 2, 1],
    [1, 7, 1],
    [2, 6, 3],
    [5, 1, 4],
    [3, 3, 4]
])

# Fungsi untuk normalisasi linear
def normalize(data):
    # Menampilkan data asli
    print("="*10, "Normalisasi Min-Max [0,1]", "="*10)
    print("Data Asli:")
    print(data)
    
    # Menentukan min dan max untuk setiap fitur
    min_vals = np.min(data, axis=0)
    max_vals = np.max(data, axis=0)
    
    # Menampilkan nilai min dan max untuk setiap fitur
    print("\nNilai minimum untuk setiap fitur:")
    print(min_vals)
    print("\nNilai maksimum untuk setiap fitur:")
    print(max_vals)
    
    # Menghitung normalisasi untuk setiap elemen
    normalized_data = (data - min_vals) / (max_vals - min_vals)
    
    # Menampilkan langkah-langkah perhitungan normalisasi
    print("\nLangkah-langkah perhitungan normalisasi:")
    for j in range(data.shape[1]):
        print(f"\nFitur {j+1}:")
        for i in range(data.shape[0]):
            norm_value = (data[i, j] - min_vals[j]) / (max_vals[j] - min_vals[j])
            print(f"  Data {i+1}: {data[i, j]} -> ({data[i, j]}-{min_vals[j]}) / ({max_vals[j]} - {min_vals[j]}) = {norm_value:.4f}")

    # Menampilkan data yang telah dinormalisasi
    print("\nData setelah normalisasi:")
    print(np.round(normalized_data, 4))
    return normalized_data

# Menjalankan normalisasi
normalized_data = normalize(data)

========== Normalisasi Min-Max [0,1] ==========
Data Asli:
[[0 2 1]
 [1 7 1]
 [2 6 3]
 [5 1 4]
 [3 3 4]]

Nilai minimum untuk setiap fitur:
[0 1 1]

Nilai maksimum untuk setiap fitur:
[5 7 4]

Langkah-langkah perhitungan normalisasi:

Fitur 1:
  Data 1: 0 -> (0-0) / (5 - 0) = 0.0000
  Data 2: 1 -> (1-0) / (5 - 0) = 0.2000
  Data 3: 2 -> (2-0) / (5 - 0) = 0.4000
  Data 4: 5 -> (5-0) / (5 - 0) = 1.0000
  Data 5: 3 -> (3-0) / (5 - 0) = 0.6000

Fitur 2:
  Data 1: 2 -> (2-1) / (7 - 1) = 0.1667
  Data 2: 7 -> (7-1) / (7 - 1) = 1.0000
  Data 3: 6 -> (6-1) / (7 - 1) = 0.8333
  Data 4: 1 -> (1-1) / (7 - 1) = 0.0000
  Data 5: 3 -> (3-1) / (7 - 1) = 0.3333

Fitur 3:
  Data 1: 1 -> (1-1) / (4 - 1) = 0.0000
  Data 2: 1 -> (1-1) / (4 - 1) = 0.0000
  Data 3: 3 -> (3-1) / (4 - 1) = 0.6667
  Data 4: 4 -> (4-1) / (4 - 1) = 1.0000
  Data 5: 4 -> (4-1) / (4 - 1) = 1.0000

Data setelah normalisasi:
[[0.     0.1667 0.    ]
 [0.2    1.     0.    ]
 [0.4    0.8333 0.6667]
 [1.     0.     1.    ]
 [0.6    0.33

In [2]:
import numpy as np

# Dataset
data = np.array([
    [0, 2, 1],
    [1, 7, 1],
    [2, 6, 3],
    [5, 1, 4],
    [3, 3, 4]
])

# Fungsi untuk normalisasi Min-Max ke rentang [-1, 1]
def normalize_min_max(data):
    # Menampilkan data asli
    print("="*10, "Normalisasi Min-Max [-1,1]", "="*10)
    print("Data Asli:")
    print(data)
    
    # Menentukan min dan max untuk setiap fitur
    min_vals = np.min(data, axis=0)
    max_vals = np.max(data, axis=0)
    
    # Menampilkan nilai min dan max untuk setiap fitur
    print("\nNilai minimum untuk setiap fitur:")
    print(min_vals)
    print("\nNilai maksimum untuk setiap fitur:")
    print(max_vals)
    
    # Menghitung normalisasi untuk setiap elemen ke rentang [-1, 1]
    normalized_data = 2 * ((data - min_vals) / (max_vals - min_vals)) - 1
    
    # Menampilkan langkah-langkah perhitungan normalisasi
    print("\nLangkah-langkah perhitungan normalisasi:")
    for j in range(data.shape[1]):  # Untuk setiap fitur (kolom)
        print(f"\nFitur {j+1}:")
        for i in range(data.shape[0]):  # Untuk setiap data point (baris)
            norm_value = 2 * (data[i, j] - min_vals[j]) / (max_vals[j] - min_vals[j]) - 1
            print(f"  x̄ {i+1}{j+1}: {data[i, j]} -> ({data[i, j]} - {min_vals[j]}) / ({max_vals[j]} - {min_vals[j]}) = {norm_value:.4f}")
            
    # Menampilkan data yang telah dinormalisasi
    print("\nData setelah normalisasi:")
    print(np.round(normalized_data, 4))
    return normalized_data

# Menjalankan normalisasi Min-Max ke rentang [-1, 1]
normalized_data = normalize_min_max(data)

========== Normalisasi Min-Max [-1,1] ==========
Data Asli:
[[0 2 1]
 [1 7 1]
 [2 6 3]
 [5 1 4]
 [3 3 4]]

Nilai minimum untuk setiap fitur:
[0 1 1]

Nilai maksimum untuk setiap fitur:
[5 7 4]

Langkah-langkah perhitungan normalisasi:

Fitur 1:
  x̄ 11: 0 -> (0 - 0) / (5 - 0) = -1.0000
  x̄ 21: 1 -> (1 - 0) / (5 - 0) = -0.6000
  x̄ 31: 2 -> (2 - 0) / (5 - 0) = -0.2000
  x̄ 41: 5 -> (5 - 0) / (5 - 0) = 1.0000
  x̄ 51: 3 -> (3 - 0) / (5 - 0) = 0.2000

Fitur 2:
  x̄ 12: 2 -> (2 - 1) / (7 - 1) = -0.6667
  x̄ 22: 7 -> (7 - 1) / (7 - 1) = 1.0000
  x̄ 32: 6 -> (6 - 1) / (7 - 1) = 0.6667
  x̄ 42: 1 -> (1 - 1) / (7 - 1) = -1.0000
  x̄ 52: 3 -> (3 - 1) / (7 - 1) = -0.3333

Fitur 3:
  x̄ 13: 1 -> (1 - 1) / (4 - 1) = -1.0000
  x̄ 23: 1 -> (1 - 1) / (4 - 1) = -1.0000
  x̄ 33: 3 -> (3 - 1) / (4 - 1) = 0.3333
  x̄ 43: 4 -> (4 - 1) / (4 - 1) = 1.0000
  x̄ 53: 4 -> (4 - 1) / (4 - 1) = 1.0000

Data setelah normalisasi:
[[-1.     -0.6667 -1.    ]
 [-0.6     1.     -1.    ]
 [-0.2     0.6667  0.3333]
 [ 1